param(
    [string]$TunnelName = "",
    [string]$ConfigPath = "$HOME\.cloudflared\config.yml"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$SampleTunnelId = "12345678-90ab-cdef-1234-567890abcdef"
$SampleHostname = "print.example.com"

function Fail {
    param([string]$Message)
    Write-Error $Message
    exit 1
}

function Read-ConfigValue {
    param(
        [string]$Path,
        [string]$Key
    )

    $pattern = "^\s*$([regex]::Escape($Key))\s*:\s*(.+?)\s*$"

    foreach ($line in Get-Content -Path $Path) {
        if ($line -match $pattern) {
            return $Matches[1].Trim().Trim("'`"")
        }
    }

    return $null
}

function Resolve-UserPath {
    param([string]$PathValue)

    if ([string]::IsNullOrWhiteSpace($PathValue)) {
        return $null
    }

    $expanded = [Environment]::ExpandEnvironmentVariables($PathValue.Trim())

    if ($expanded.StartsWith("~/") -or $expanded.StartsWith("~\")) {
        return Join-Path $HOME $expanded.Substring(2)
    }

    return $expanded
}

function Read-IngressFields {
    param([string]$Path)

    $hostname = $null
    $originService = $null
    $inIngress = $false

    foreach ($line in Get-Content -Path $Path) {
        if ($line -match "^\s*ingress\s*:\s*$") {
            $inIngress = $true
            continue
        }

        if (-not $inIngress) {
            continue
        }

        if (-not $hostname -and $line -match "^\s*-\s*hostname\s*:\s*(.+?)\s*(?:#.*)?$") {
            $hostname = $Matches[1].Trim().Trim("'`"")
            continue
        }

        if ($line -match "^\s*(?:-\s*)?service\s*:\s*(.+?)\s*(?:#.*)?$") {
            $serviceCandidate = $Matches[1].Trim().Trim("'`"")
            if (-not $originService -and $serviceCandidate -match "^https?://") {
                $originService = $serviceCandidate
            }
        }
    }

    return @{
        Hostname = $hostname
        OriginService = $originService
    }
}

# Runs a named cloudflared tunnel using the provided config file.
# Prerequisites:
#   - cloudflared installed (choco install cloudflared)
#   - tunnel created: cloudflared tunnel create <tunnel-name>
#   - DNS route set:   cloudflared tunnel route dns <tunnel-name> print.example.com
#   - config.yml placed at $ConfigPath (see config/cloudflared/config.yml.example)

if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
    Fail "cloudflared is not installed. Install with: choco install cloudflared"
}

if (-not (Test-Path $ConfigPath)) {
    Fail "Config file not found at $ConfigPath. Copy config/cloudflared/config.yml.example and update it."
}

$originCertPath = Join-Path $HOME ".cloudflared\cert.pem"
if (-not (Test-Path $originCertPath)) {
    Write-Warning "No origin cert found at $originCertPath. If you still need to create or list tunnels, run: cloudflared tunnel login"
}

$tunnelFromConfig = Read-ConfigValue -Path $ConfigPath -Key "tunnel"
$credentialsFileRaw = Read-ConfigValue -Path $ConfigPath -Key "credentials-file"
$credentialsFilePath = Resolve-UserPath -PathValue $credentialsFileRaw
$ingress = Read-IngressFields -Path $ConfigPath

if ([string]::IsNullOrWhiteSpace($tunnelFromConfig)) {
    Fail "Missing 'tunnel' in $ConfigPath."
}

if ($tunnelFromConfig -eq $SampleTunnelId) {
    Fail "Config still uses placeholder tunnel id ($SampleTunnelId). Replace it with your real tunnel id."
}

if ([string]::IsNullOrWhiteSpace($credentialsFileRaw)) {
    Fail "Missing 'credentials-file' in $ConfigPath."
}

if ($credentialsFileRaw -match [regex]::Escape($SampleTunnelId)) {
    Fail "Config still uses placeholder credentials-file path. Update it to the JSON generated by cloudflared tunnel create."
}

if (-not (Test-Path $credentialsFilePath)) {
    Fail "Tunnel credentials file not found at $credentialsFilePath. Run 'cloudflared tunnel create <name>' or fix credentials-file path."
}

if ([string]::IsNullOrWhiteSpace($ingress.Hostname)) {
    Fail "Missing ingress hostname in $ConfigPath."
}

if ($ingress.Hostname -eq $SampleHostname) {
    Fail "Ingress hostname is still placeholder '$SampleHostname'. Set it to your real DNS hostname."
}

if (-not [string]::IsNullOrWhiteSpace($ingress.OriginService) -and $ingress.OriginService -notmatch "^https?://127\.0\.0\.1:\d+/?$") {
    Write-Warning "Origin service is '$($ingress.OriginService)'. Expected a local HTTP endpoint such as 'http://127.0.0.1:5001'."
}

$effectiveTunnel = if ([string]::IsNullOrWhiteSpace($TunnelName)) { $tunnelFromConfig } else { $TunnelName }

if (-not [string]::IsNullOrWhiteSpace($TunnelName) -and $TunnelName -ne $tunnelFromConfig) {
    Write-Warning "TunnelName override '$TunnelName' differs from config tunnel '$tunnelFromConfig'."
}

Write-Host "Cloudflare tunnel preflight passed:"
Write-Host "  Config:   $ConfigPath"
Write-Host "  Tunnel:   $effectiveTunnel"
Write-Host "  Hostname: $($ingress.Hostname)"
if (-not [string]::IsNullOrWhiteSpace($ingress.OriginService)) {
    Write-Host "  Origin:   $($ingress.OriginService)"
}

Write-Host "Starting cloudflared tunnel '$effectiveTunnel' using $ConfigPath ..."
& cloudflared tunnel --config $ConfigPath run $effectiveTunnel
exit $LASTEXITCODE
